services:
  postgres:
    image: postgres:16.2
    container_name: weather-postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
    container_name: weather-server
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:${SERVER_INTERNAL_PORT}"
    depends_on:
      - postgres

  client:
    build:
      context: ./client
    container_name: weather-client
    ports:
      - "${CLIENT_PORT}:${CLIENT_INTERNAL_PORT}"
    environment:
      VITE_API_BASE: http://localhost:${SERVER_INTERNAL_PORT}
    depends_on:
      - server

volumes:
  postgres_data: