services:
  postgres:
    image: postgres:16.2
    container_name: weather-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: weather-server
    restart: always
    env_file:
      - ${SERVER_ENV_FILE}
    ports:
      - "${SERVER_PORT}:${SERVER_INTERNAL_PORT}"
    depends_on:
      - postgres
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: weather-client
    env_file:
      - ${CLIENT_ENV_FILE}
    ports:
      - "${CLIENT_PORT}:${CLIENT_INTERNAL_PORT}"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  postgres_data:
