export const LOGGER_BATCH_SIZE = 20;
export const LOGGER_FLUSH_INTERVAL_IN_MS = 60000;

export const LOGGER_MAX_RETRY_COUNT = 5;
export const LOGGER_RETRY_DELAY_IN_MS = 3000;

export const LOGGER_DEDUPLICATION_WINDOW_IN_MS = 1000;
export const LOGGER_DEDUPLICATION_CLEANUP_INTERVAL_IN_MS = 10000;

export const LOGGER_MAX_LOGS_PER_MINUTE = 3000;
export const LOGGER_RATE_LIMIT_WINDOW_IN_MS = 60000;
